title: Synapse # Site title - you can change this to the name of your own site.
markdown: kramdown # Specifies kramdown as the Markdown processor. You can keep this as is.
url: https://amrl.cs.utexas.edu # The base URL for your site - change this to your site's URL.

# kramdown settings
kramdown:
  input: GFM # Use GitHub Flavored Markdown (GFM) as the input format.
  auto_ids: true # Automatically generate IDs for headers to enable anchor linking.
  hard_wrap: false # Do not treat newlines as hard breaks. Useful for more control over text formatting.
  syntax_highlighter: rouge # Use Rouge for syntax highlighting. It's a pure-ruby syntax highlighter.

# Build settings
exclude:
  - node_modules/ # Exclude directories and files from the build.
  - .jekyll-cache/
  - .DS_Store